export type Token = {
  id: string
  name: string
  ticker: string
  emoji: string
  creator: string
  underlying: "SOL-PERP" | "BTC-PERP" | "ETH-PERP" | "DOGE-PERP"
  leverage: 2 | 3 | 5 | 10
  direction: "LONG" | "SHORT"
  marketCap: number
  progress: number // 0-100 to graduation
  replies: number
  ageMinutes: number
  change24h: number
  liqDistance: number // % until liquidation, lower = scarier
  description: string
}

export const tokens: Token[] = [
  {
    id: "1",
    name: "Mega Sol Bull",
    ticker: "MSOL5",
    emoji: "🚀",
    creator: "9xQe...4Rk",
    underlying: "SOL-PERP",
    leverage: 5,
    direction: "LONG",
    marketCap: 64200,
    progress: 93,
    replies: 1240,
    ageMinutes: 42,
    change24h: 312.4,
    liqDistance: 18,
    description: "sol to 1000. 5x leveraged. wagmi or rekt. no in-between.",
  },
  {
    id: "2",
    name: "Bitcoin Bear God",
    ticker: "BEARBTC",
    emoji: "🐻",
    creator: "Hk2p...9Lm",
    underlying: "BTC-PERP",
    leverage: 3,
    direction: "SHORT",
    marketCap: 28400,
    progress: 41,
    replies: 412,
    ageMinutes: 18,
    change24h: 89.2,
    liqDistance: 32,
    description: "btc 50k incoming. shorting with conviction.",
  },
  {
    id: "3",
    name: "Ethereum Maxi",
    ticker: "ETH3X",
    emoji: "💎",
    creator: "Zx81...2Ap",
    underlying: "ETH-PERP",
    leverage: 3,
    direction: "LONG",
    marketCap: 51200,
    progress: 74,
    replies: 822,
    ageMinutes: 91,
    change24h: 201.7,
    liqDistance: 24,
    description: "eth flippening soon. diamond hands only.",
  },
  {
    id: "4",
    name: "Doge to Mars",
    ticker: "DOGE10",
    emoji: "🐕",
    creator: "Mn4q...7Vc",
    underlying: "DOGE-PERP",
    leverage: 10,
    direction: "LONG",
    marketCap: 12800,
    progress: 18,
    replies: 188,
    ageMinutes: 7,
    change24h: 422.1,
    liqDistance: 8,
    description: "elon tweet incoming. 10x maximum cope.",
  },
  {
    id: "5",
    name: "Sol Short Squeeze",
    ticker: "SHRSOL",
    emoji: "📉",
    creator: "Pl9k...3Nb",
    underlying: "SOL-PERP",
    leverage: 2,
    direction: "SHORT",
    marketCap: 19400,
    progress: 28,
    replies: 94,
    ageMinutes: 124,
    change24h: -42.3,
    liqDistance: 56,
    description: "sol top is in. screenshot this.",
  },
  {
    id: "6",
    name: "Berachain Bull",
    ticker: "BERA5",
    emoji: "🐻‍❄️",
    creator: "Ty3w...8Df",
    underlying: "ETH-PERP",
    leverage: 5,
    direction: "LONG",
    marketCap: 8200,
    progress: 11,
    replies: 56,
    ageMinutes: 4,
    change24h: 612.0,
    liqDistance: 14,
    description: "low cap gem. early bera energy.",
  },
  {
    id: "7",
    name: "WIF Hat 5x",
    ticker: "WIF5X",
    emoji: "🎩",
    creator: "Qa8r...1Ws",
    underlying: "SOL-PERP",
    leverage: 5,
    direction: "LONG",
    marketCap: 41100,
    progress: 59,
    replies: 588,
    ageMinutes: 67,
    change24h: 144.9,
    liqDistance: 21,
    description: "dogwifhat with leverage. self explanatory.",
  },
  {
    id: "8",
    name: "Pepe Long Forever",
    ticker: "PEPE3",
    emoji: "🐸",
    creator: "Vb2x...5Hg",
    underlying: "ETH-PERP",
    leverage: 3,
    direction: "LONG",
    marketCap: 33700,
    progress: 48,
    replies: 320,
    ageMinutes: 38,
    change24h: 78.4,
    liqDistance: 29,
    description: "pepe never dies. 3x conviction play.",
  },
  {
    id: "9",
    name: "Anti Btc Maxis",
    ticker: "NOBTC",
    emoji: "🔻",
    creator: "Cx7n...4Jk",
    underlying: "BTC-PERP",
    leverage: 5,
    direction: "SHORT",
    marketCap: 6400,
    progress: 9,
    replies: 22,
    ageMinutes: 2,
    change24h: 1240.0,
    liqDistance: 6,
    description: "btc going to 30k. fade the maxis.",
  },
  {
    id: "10",
    name: "Solana Summer",
    ticker: "SOLSUM",
    emoji: "☀️",
    creator: "Re5t...8Yu",
    underlying: "SOL-PERP",
    leverage: 2,
    direction: "LONG",
    marketCap: 22100,
    progress: 32,
    replies: 142,
    ageMinutes: 58,
    change24h: 56.8,
    liqDistance: 44,
    description: "summer is here. comfy 2x long.",
  },
  {
    id: "11",
    name: "Mega Doge Short",
    ticker: "DSHORT",
    emoji: "💀",
    creator: "Fg4h...2Mn",
    underlying: "DOGE-PERP",
    leverage: 5,
    direction: "SHORT",
    marketCap: 4200,
    progress: 6,
    replies: 18,
    ageMinutes: 1,
    change24h: 89.0,
    liqDistance: 12,
    description: "doge is overvalued. 5x short. ngmi.",
  },
  {
    id: "12",
    name: "Eth Killer Killer",
    ticker: "EKK10",
    emoji: "⚔️",
    creator: "As9d...6Lp",
    underlying: "ETH-PERP",
    leverage: 10,
    direction: "SHORT",
    marketCap: 15800,
    progress: 22,
    replies: 78,
    ageMinutes: 14,
    change24h: 312.0,
    liqDistance: 4,
    description: "10x short eth. literally about to liquidate. degen only.",
  },
]

export type LiveTrade = {
  id: string
  ticker: string
  side: "BUY" | "SELL"
  amount: number
  user: string
  ago: string
}

export const liveTrades: LiveTrade[] = [
  { id: "t1", ticker: "MSOL5", side: "BUY", amount: 4.2, user: "9xQe", ago: "1s" },
  { id: "t2", ticker: "DOGE10", side: "BUY", amount: 0.8, user: "Mn4q", ago: "2s" },
  { id: "t3", ticker: "BEARBTC", side: "SELL", amount: 1.5, user: "Hk2p", ago: "3s" },
  { id: "t4", ticker: "ETH3X", side: "BUY", amount: 12.4, user: "Zx81", ago: "4s" },
  { id: "t5", ticker: "WIF5X", side: "BUY", amount: 2.2, user: "Qa8r", ago: "5s" },
  { id: "t6", ticker: "PEPE3", side: "SELL", amount: 0.4, user: "Vb2x", ago: "6s" },
  { id: "t7", ticker: "NOBTC", side: "BUY", amount: 8.1, user: "Cx7n", ago: "7s" },
  { id: "t8", ticker: "SOLSUM", side: "BUY", amount: 3.3, user: "Re5t", ago: "8s" },
  { id: "t9", ticker: "EKK10", side: "SELL", amount: 0.9, user: "As9d", ago: "9s" },
  { id: "t10", ticker: "BERA5", side: "BUY", amount: 1.1, user: "Ty3w", ago: "11s" },
  { id: "t11", ticker: "SHRSOL", side: "SELL", amount: 0.6, user: "Pl9k", ago: "13s" },
  { id: "t12", ticker: "DSHORT", side: "BUY", amount: 0.3, user: "Fg4h", ago: "15s" },
]
