[package]
name = "leveraged_meme"
version = "0.1.0"
description = "Leveraged Meme Trading Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "leveraged_meme"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.28.0", features = ["metadata"] }

[profile.release]
overflow-checks = true
