version: '3.8'

services:
  builder:
    build: .
    volumes:
      - ./target:/workspace/target
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./Cargo.lock:/workspace/Cargo.lock
      - ./Anchor.toml:/workspace/Anchor.toml
      - ./src:/workspace/src
    command: anchor build
